In [1]:
import autograd 

import autograd.numpy as np
import autograd.scipy as sp
from numpy.polynomial.hermite import hermgauss

import sys
sys.path.insert(0, '../libraries/')

import structure_model_lib 
import data_utils

import paragami

# Draw data

In [2]:
n_obs = 10
n_loci = 5
n_pop = n_loci

# population allele frequencies
p1 = 1.0
p0 = 0.0
pop_allele_freq = np.maximum(np.eye(n_loci, n_pop) * p1, p0)

# individual admixtures
ind_admix_propn = np.random.choice(n_pop, n_obs)
ind_admix_propn = data_utils.get_one_hot(ind_admix_propn, nb_classes = n_pop)

In [3]:
pop_allele_freq

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [4]:
ind_admix_propn

array([[1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [5]:
g_obs = data_utils.draw_data(pop_allele_freq, ind_admix_propn)

In [6]:
g_obs.argmax(axis = 2)

array([[2, 0, 0, 0, 0],
       [0, 0, 0, 2, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [2, 0, 0, 0, 0],
       [0, 2, 0, 0, 0]])